use std::{path::PathBuf, sync::Arc};

use cucumber::World;
use ed25519_dalek::SigningKey;
use oc_keyagent::{AuditLog, EventType, PasskeyVerifier};
use oc_policy::{Decision, DenyReason, PolicyState, PolicyV2};
use oc_proto::PasskeyAuthorization;
use oc_session_key::{
    GrantReceipt, MockRpcClient, MockRpcCounters, OwnerKey, PublicKey, SessionPrivateKey,
};

pub mod steps;

/// Resolve the workspace root from the conformance crate's `CARGO_MANIFEST_DIR`.
///
/// The conformance crate lives at `<workspace>/crates/oc-conformance/`, so the
/// workspace root is two ancestors up. Step definitions call this instead of
/// using `env!("CARGO_MANIFEST_DIR")` directly (which would point at the
/// conformance crate dir, not the workspace root).
pub fn workspace_root() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .ancestors()
        .nth(2)
        .expect("workspace root not found — conformance crate must live at <workspace>/crates/oc-conformance/")
        .to_path_buf()
}

/// Conformance test World.
///
/// Holds the component-level state needed to drive the BDD scenarios in
/// `crates/oc-conformance/tests/conformance/steps/`. Per the T22 design,
/// steps orchestrate EXISTING components directly (PasskeyVerifier, AuditLog,
/// SessionKeyProvider, PolicyState) rather than going through
/// `oc_keyagent::handler::dispatch()`.
///
/// `Debug` is implemented manually because several fields (`AuditLog`,
/// `PasskeyVerifier`, `HardenedBytes`) intentionally do not derive `Debug`.
#[derive(World)]
#[world(init = Self::new)]
pub struct ConformanceWorld {
    // --- T22: Session Key Lifecycle state ---
    /// Ed25519 device key used to sign audit entries.
    pub device_key: Option<SigningKey>,
    /// Open audit log (file lives inside a leaked `tempfile::TempDir`).
    pub audit_log: Option<AuditLog>,
    /// Path to the audit log file (kept for diagnostics).
    pub audit_path: Option<PathBuf>,
    /// Key-Agent-side Passkey verifier (stores pubkey + pending challenges).
    pub passkey_verifier: Option<PasskeyVerifier>,
    /// Ed25519 signing key used to sign Passkey challenges in tests.
    pub passkey_signing_key: Option<SigningKey>,
    /// Registered Passkey credential ID bytes.
    pub passkey_credential_id: Option<Vec<u8>>,
    /// Owner's signing key for the current scenario.
    pub owner_key: Option<OwnerKey>,
    /// Ephemeral session private key (issued in CreateSessionKey flow).
    pub session_priv: Option<SessionPrivateKey>,
    /// Ephemeral session public key (issued in CreateSessionKey flow).
    pub session_pubkey: Option<PublicKey>,
    /// Active session_key_id for the scenario.
    pub session_key_id: Option<String>,
    /// Drafted policy for the scenario.
    pub policy: Option<PolicyV2>,
    /// Persisted policy state (used by revoke / expiry scenarios).
    pub policy_state: Option<PolicyState>,
    /// Path to the policy state file.
    pub policy_state_path: Option<PathBuf>,
    /// Mock RPC client (consumed by providers; counters survive via Arc).
    pub mock_rpc: Option<MockRpcClient>,
    /// Counters for the most recent MockRpcClient instance.
    pub mock_rpc_counters: Option<Arc<MockRpcCounters>>,
    /// Receipt returned by the most recent `grant()` call.
    pub grant_receipt: Option<GrantReceipt>,
    /// Most recent Policy decision (Allow / Deny(reason)).
    pub last_decision: Option<Decision>,
    /// Most recent DenyReason (if any).
    pub last_deny_reason: Option<DenyReason>,
    /// Most recent audit EventType appended.
    pub last_audit_event: Option<EventType>,
    /// Most recent error message (for diagnostic asserts).
    pub last_error: Option<String>,

    // --- T23: Passkey Authorization state ---
    /// Challenges generated by the Key-Agent in the current scenario
    /// (used by Scenario 2 to assert fresh 32-byte nonces + single-use
    /// consumption). Each challenge is exactly 32 bytes.
    pub challenges: Vec<[u8; 32]>,
    /// A PasskeyAuthorization captured from a previous (successful) verify
    /// call, used by Scenario 3 to attempt a replay.
    pub captured_auth: Option<PasskeyAuthorization>,

    // --- T22 scenario 4: ConnectRPC method surface ---
    /// ConnectRPC methods the Agent can call. Asserted to never expose
    /// Owner key / BIP-32 root / mnemonic.
    pub connectrpc_methods: Vec<&'static str>,

    // --- T31: Policy Alert state ---
    /// Alerts captured by the RecordingAlertSink during the current scenario.
    /// `None` if no sink has been installed; `Some(Arc<Mutex<Vec<HumanAlert>>>)`
    /// otherwise. The Arc is shared between the World and the sink installed
    /// in `policy_state.alert_sink`.
    pub captured_alerts: Option<std::sync::Arc<std::sync::Mutex<Vec<oc_policy::HumanAlert>>>>,
}

impl std::fmt::Debug for ConformanceWorld {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ConformanceWorld")
            .field("audit_log_present", &self.audit_log.is_some())
            .field("audit_path", &self.audit_path)
            .field("passkey_verifier_present", &self.passkey_verifier.is_some())
            .field("passkey_signing_key_present", &self.passkey_signing_key.is_some())
            .field("passkey_credential_id_present", &self.passkey_credential_id.is_some())
            .field("owner_key_present", &self.owner_key.is_some())
            .field("session_priv_present", &self.session_priv.is_some())
            .field("session_pubkey_present", &self.session_pubkey.is_some())
            .field("session_key_id", &self.session_key_id)
            .field("policy_present", &self.policy.is_some())
            .field("policy_state_present", &self.policy_state.is_some())
            .field("policy_state_path", &self.policy_state_path)
            .field("mock_rpc_present", &self.mock_rpc.is_some())
            .field("mock_rpc_counters_present", &self.mock_rpc_counters.is_some())
            .field("grant_receipt", &self.grant_receipt)
            .field("last_decision", &self.last_decision)
            .field("last_deny_reason", &self.last_deny_reason)
            .field("last_audit_event", &self.last_audit_event)
            .field("last_error", &self.last_error)
            .field("challenges_count", &self.challenges.len())
            .field("captured_auth_present", &self.captured_auth.is_some())
            .field("connectrpc_methods", &self.connectrpc_methods)
            .field("captured_alerts_present", &self.captured_alerts.is_some())
            .finish()
    }
}

impl ConformanceWorld {
    fn new() -> Self {
        Self {
            device_key: None,
            audit_log: None,
            audit_path: None,
            passkey_verifier: None,
            passkey_signing_key: None,
            passkey_credential_id: None,
            owner_key: None,
            session_priv: None,
            session_pubkey: None,
            session_key_id: None,
            policy: None,
            policy_state: None,
            policy_state_path: None,
            mock_rpc: None,
            mock_rpc_counters: None,
            grant_receipt: None,
            last_decision: None,
            last_deny_reason: None,
            last_audit_event: None,
            last_error: None,
            challenges: Vec::new(),
            captured_auth: None,
            connectrpc_methods: vec![
                "ListWallets",
                "GetBalance",
                "CreateSessionKey",
                "RevokeSessionKey",
                "ListSessionKeys",
                "SignTransaction",
                "SignUserOp",
                "SignMessage",
                "SignTypedData",
                "PayX402",
                "PayMPP",
                "GetPaymentHistory",
            ],
            captured_alerts: None,
        }
    }
}

#[tokio::main]
async fn main() {
    let features = workspace_root().join("specs/2026-07-22-01-unified-vault/features");
    ConformanceWorld::run(features.as_path()).await;
}
