//! oc-proto — ConnectRPC AgentService proto definitions for OneCipher.
//!
//! Generated by `prost-build` from `proto/agent.proto`. The generated types
//! are re-exported at the crate root for downstream use.
//!
//! ## Phase 1 scope
//!
//! All `AgentService` RPCs are defined EXCEPT `ConnectDapp` / `DisconnectDapp`
//! (WalletConnect v2 deferred to Phase 2).
//!
//! ## Deviations from `docs/design.md` §5.3
//!
//! - `google.protobuf.Empty` is replaced by a local `Empty` message to avoid vendoring well-known
//!   types (ponytail ladder — minimum dep).
//! - `Policy`, `PolicyRulesV2`, `BudgetAllocation` are mirrored as proto messages (wire-format
//!   types) rather than imported from `oc-policy`.
//! - `deny_reason` on `PayX402Response` is a proto `string` field (per design.md) for forward
//!   compatibility; the `DenyReason` enum is defined separately for type-safe use.

#![deny(unsafe_code)]

pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/onecipher.agent.v1.rs"));
}

pub use pb::*;

#[cfg(test)]
mod tests {
    use prost::Message;

    use super::*;

    // -----------------------------------------------------------------------
    // Round-trip helpers
    // -----------------------------------------------------------------------

    fn roundtrip<M>(msg: &M) -> M
    where
        M: Message + Clone + PartialEq + std::fmt::Debug + Default,
    {
        let buf = msg.encode_to_vec();
        M::decode(buf.as_slice()).expect("decode must succeed for a validly-encoded message")
    }

    // -----------------------------------------------------------------------
    // 1. PasskeyAuthorization round-trip
    // -----------------------------------------------------------------------

    #[test]
    fn test_passkey_authorization_roundtrip() {
        let original = PasskeyAuthorization {
            challenge: vec![0xDE, 0xAD, 0xBE, 0xEF],
            signature: vec![0x01, 0x02, 0x03, 0x04, 0x05],
            credential_id: "cred-12345".to_string(),
        };
        let decoded = roundtrip(&original);
        assert_eq!(original, decoded);
        assert_eq!(decoded.challenge, vec![0xDE, 0xAD, 0xBE, 0xEF]);
        assert_eq!(decoded.signature, vec![0x01, 0x02, 0x03, 0x04, 0x05]);
        assert_eq!(decoded.credential_id, "cred-12345");
    }

    // -----------------------------------------------------------------------
    // 2. PayX402Request round-trip (including headers map)
    // -----------------------------------------------------------------------

    #[test]
    fn test_payx402_request_roundtrip() {
        let mut headers = std::collections::HashMap::new();
        headers.insert("X-Idempotency-Key".to_string(), "abc-123".to_string());
        headers.insert("Authorization".to_string(), "Bearer token".to_string());
        let original = PayX402Request {
            session_key_id: "sk-7f3a".to_string(),
            url: "https://pay.example/x402".to_string(),
            method: "POST".to_string(),
            body: b"{\"amount\":100}".to_vec(),
            headers,
            ..Default::default()
        };
        let decoded = roundtrip(&original);
        assert_eq!(original, decoded);
        assert_eq!(decoded.session_key_id, "sk-7f3a");
        assert_eq!(decoded.method, "POST");
        assert_eq!(decoded.body, b"{\"amount\":100}");
        assert_eq!(decoded.headers.len(), 2);
        assert_eq!(decoded.headers.get("X-Idempotency-Key"), Some(&"abc-123".to_string()));
    }

    // -----------------------------------------------------------------------
    // 3. PayX402Response round-trip (including deny_reason string)
    // -----------------------------------------------------------------------

    #[test]
    fn test_payx402_response_roundtrip() {
        let original = PayX402Response {
            status: PaymentStatus::Deny as i32,
            receipt: vec![0xAA, 0xBB],
            retry_authorization: "retry-after-60s".to_string(),
            deny_reason: "RATE_LIMIT_MINUTE".to_string(),
            error: String::new(),
        };
        let decoded = roundtrip(&original);
        assert_eq!(original, decoded);
        assert_eq!(decoded.status, PaymentStatus::Deny as i32);
        assert_eq!(decoded.deny_reason, "RATE_LIMIT_MINUTE");
        assert_eq!(decoded.retry_authorization, "retry-after-60s");
    }

    // -----------------------------------------------------------------------
    // 4. CreateSessionKeyRequest round-trip (auth must be present)
    // -----------------------------------------------------------------------

    #[test]
    fn test_create_session_key_request_roundtrip() {
        let auth = PasskeyAuthorization {
            challenge: vec![0x10; 32],
            signature: vec![0x20; 64],
            credential_id: "cred-abc".to_string(),
        };
        let original = CreateSessionKeyRequest {
            label: "test-session".to_string(),
            rules: None,
            budget: None,
            auth: Some(auth.clone()),
        };
        let decoded = roundtrip(&original);
        assert_eq!(original, decoded);
        // Behavioral contract: auth is a required field on CreateSessionKeyRequest.
        let decoded_auth =
            decoded.auth.as_ref().expect("auth must be present on CreateSessionKeyRequest");
        assert_eq!(decoded_auth.challenge, auth.challenge);
        assert_eq!(decoded_auth.signature, auth.signature);
        assert_eq!(decoded_auth.credential_id, auth.credential_id);
    }

    #[test]
    fn test_create_session_key_request_auth_is_required_field() {
        // Behavioral contract: PasskeyAuthorization is required on
        // CreateSessionKeyRequest. We assert the field type is Option and that
        // a request without auth can still be encoded (proto3 has no required
        // fields), but downstream callers MUST set it. This test documents the
        // expectation by encoding a request with auth and asserting presence.
        let req = CreateSessionKeyRequest {
            label: "needs-auth".to_string(),
            rules: None,
            budget: None,
            auth: Some(PasskeyAuthorization {
                challenge: vec![1, 2, 3],
                signature: vec![4, 5, 6],
                credential_id: "cred".to_string(),
            }),
        };
        assert!(
            req.auth.is_some(),
            "CreateSessionKeyRequest.auth MUST be set (PasskeyAuthorization required)"
        );
    }

    // -----------------------------------------------------------------------
    // 5. PaymentStatus enum values
    // -----------------------------------------------------------------------

    #[test]
    fn test_payment_status_enum_values() {
        assert_eq!(PaymentStatus::Ok as i32, 0);
        assert_eq!(PaymentStatus::Deny as i32, 1);
        assert_eq!(PaymentStatus::Error as i32, 2);
    }

    // -----------------------------------------------------------------------
    // 6. DenyReason enum values (R80 — exactly 9 variants)
    // -----------------------------------------------------------------------

    #[test]
    fn test_deny_reason_enum_values() {
        assert_eq!(DenyReason::RateLimitMinute as i32, 0);
        assert_eq!(DenyReason::RateLimitHour as i32, 1);
        assert_eq!(DenyReason::BudgetExceeded as i32, 2);
        assert_eq!(DenyReason::Whitelist as i32, 3);
        assert_eq!(DenyReason::Expired as i32, 4);
        assert_eq!(DenyReason::PasskeyForged as i32, 5);
        assert_eq!(DenyReason::PolicyMissing as i32, 6);
        assert_eq!(DenyReason::Cooldown as i32, 7);
        assert_eq!(DenyReason::Unknown as i32, 8);

        // All 9 R80 string names round-trip through as_str_name / from_str_name.
        let all = [
            DenyReason::RateLimitMinute,
            DenyReason::RateLimitHour,
            DenyReason::BudgetExceeded,
            DenyReason::Whitelist,
            DenyReason::Expired,
            DenyReason::PasskeyForged,
            DenyReason::PolicyMissing,
            DenyReason::Cooldown,
            DenyReason::Unknown,
        ];
        for v in all {
            let name = v.as_str_name();
            assert_eq!(DenyReason::from_str_name(name), Some(v));
        }
    }

    // -----------------------------------------------------------------------
    // 7. Malformed bytes must return Err, not panic
    // -----------------------------------------------------------------------

    #[test]
    fn test_decode_malformed_bytes_no_panic() {
        let garbage: Vec<u8> = vec![0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x01, 0x02];
        let result = PayX402Request::decode(garbage.as_slice());
        // It may succeed (proto3 is permissive) or fail, but must NOT panic.
        // We only assert it returns a Result.
        let _ = result;
    }

    #[test]
    fn test_decode_truncated_field_no_panic() {
        // Truncated mid-field: tag says length=10 but only 3 bytes follow.
        let truncated = vec![0x2A, 0x0A, 0x01, 0x02, 0x03];
        let _ = PayX402Request::decode(truncated.as_slice());
    }

    // -----------------------------------------------------------------------
    // 8. Empty message round-trip (encodes to 0 bytes)
    // -----------------------------------------------------------------------

    #[test]
    fn test_empty_message() {
        let empty = Empty {};
        let buf = empty.encode_to_vec();
        assert!(buf.is_empty(), "Empty message must encode to 0 bytes");
        let decoded: Empty =
            Empty::decode(buf.as_slice()).expect("decode of empty buf must succeed");
        assert_eq!(empty, decoded);
    }
}
