//! Passkey challenge-response verification.
//!
//! Per R30 / R31 / C-05: the Key-Agent NEVER trusts a UI boolean `authorized=true`.
//! It generates a fresh 32-byte nonce per high-risk operation, stores it single-use,
//! and verifies the Passkey signature against the stored public key. Reused challenges
//! are rejected with [`PasskeyError::Replay`]. Forged or missing signatures are
//! rejected with [`PasskeyError::Forged`] / [`PasskeyError::Missing`].
//!
//! ## Wire format
//!
//! `oc_proto::PasskeyAuthorization` carries three fields:
//! - `challenge: bytes`    — 32-byte nonce generated by the Key-Agent
//! - `signature: bytes`    — UI process signs `challenge || credential_id`
//! - `credential_id: string` — registered Passkey credential ID
//!
//! The proto has NO algorithm field and NO boolean `authorized` field. The
//! signature algorithm is fixed at registration time by which variant of
//! [`PasskeyPubkey`] the Key-Agent stores. R31: any boolean in the IPC
//! envelope is ignored entirely — only the cryptographic signature matters.
//!
//! ## Simplified protocol (not full WebAuthn)
//!
//! Per design.md §Detailed Design (PasskeyAuthorization): the signed message
//! is the concatenation `challenge || credential_id`. This is intentionally
//! simpler than full WebAuthn authenticator data (R30 — Phase 1 scope).

use std::{
    collections::{HashMap, HashSet},
    fs,
    os::unix::fs::PermissionsExt,
    path::{Path, PathBuf},
};

use oc_proto::PasskeyAuthorization;
use rand::RngExt;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PasskeyError {
    /// Signature did not verify against the stored public key, or signature
    /// bytes could not be parsed as a valid P-256 / Ed25519 signature.
    #[error("passkey signature forged")]
    Forged,
    /// The challenge was not present in `pending_challenges` — either it was
    /// never issued by this Key-Agent, or it was already consumed (replay).
    #[error("passkey challenge replayed")]
    Replay,
    /// The `PasskeyAuthorization` was structurally incomplete: challenge was
    /// not exactly 32 bytes, or `credential_id` was empty.
    #[error("passkey authorization missing")]
    Missing,
    /// The `credential_id` in the authorization did not match the one bound
    /// to the stored Passkey public key at registration time.
    #[error("passkey credential ID mismatch")]
    CredentialMismatch,
}

/// Stored Passkey public key. The algorithm is fixed at registration time.
///
/// Per R30/R44: the Key-Agent stores the Passkey public key locally at
/// wallet-creation time and verifies `PasskeyAuthorization.signature` itself.
/// The proto message `PasskeyAuthorization` carries no algorithm field, so
/// the algorithm is fixed by which variant the Key-Agent holds.
pub enum PasskeyPubkey {
    /// P-256 (WebAuthn default — SECP256R1).
    P256(p256::ecdsa::VerifyingKey),
    /// Ed25519 fallback.
    Ed25519(ed25519_dalek::VerifyingKey),
}

/// Key-Agent-side Passkey verifier.
///
/// Per R30/R31/C-05: the Key-Agent NEVER trusts a UI boolean. It generates
/// fresh 32-byte nonces, stores them single-use, and verifies each
/// [`PasskeyAuthorization`] signature against the stored public key.
///
/// ```
/// # use oc_keyagent::passkey::{PasskeyVerifier, PasskeyPubkey, PasskeyError};
/// # use oc_proto::PasskeyAuthorization;
/// # fn mk(verifier: &mut PasskeyVerifier, auth: PasskeyAuthorization) {
/// // Generate a fresh challenge before sending the request to the UI.
/// let _challenge = verifier.generate_challenge();
/// // ... UI signs and returns a PasskeyAuthorization ...
/// // Key-Agent verifies the signature itself — never trusts a boolean.
/// let _: Result<(), PasskeyError> = verifier.verify(&auth);
/// # }
/// ```
pub struct PasskeyVerifier {
    stored_pubkey: PasskeyPubkey,
    stored_credential_id: Vec<u8>,
    pending_challenges: HashSet<[u8; 32]>,
}

impl PasskeyVerifier {
    /// Construct a verifier bound to a stored public key and credential ID.
    ///
    /// The credential ID is the bytes of the registered Passkey credential
    /// (compared byte-for-byte against `auth.credential_id` on every verify).
    pub fn new(pubkey: PasskeyPubkey, credential_id: Vec<u8>) -> Self {
        Self {
            stored_pubkey: pubkey,
            stored_credential_id: credential_id,
            pending_challenges: HashSet::new(),
        }
    }

    /// Generate a fresh 32-byte challenge nonce. NEVER repeats (cryptographic RNG).
    ///
    /// Per R30 / `passkey_authorization.feature` "fresh 32-byte nonce": each
    /// call returns 32 bytes of cryptographically random data drawn from
    /// [`rand::rngs::OsRng`] (the kernel CSPRNG), inserted into
    /// `pending_challenges`. The nonce is single-use: it is removed from the
    /// set after a successful [`Self::verify`].
    pub fn generate_challenge(&mut self) -> [u8; 32] {
        let mut nonce = [0u8; 32];
        loop {
            // OsRng is the kernel CSPRNG (getrandom / BoringSSL) — never fails.
            rand::rng().fill(&mut nonce);
            if self.pending_challenges.insert(nonce) {
                break;
            }
            // Astronomically unlikely collision — regenerate.
        }
        nonce
    }

    /// Verify a [`PasskeyAuthorization`] against the stored pubkey + pending challenge.
    ///
    /// Order of checks (per R31 — boolean fields in the IPC envelope are
    /// ignored entirely; only signature bytes are consulted):
    ///
    /// 1. **Structural completeness** — `challenge` must be exactly 32 bytes and `credential_id`
    ///    non-empty. Otherwise → [`PasskeyError::Missing`]. (An empty / malformed `signature` is
    ///    NOT treated as `Missing` here; it falls through to step 4 and returns `Forged`. This
    ///    matches the R31 contract: a UI that sends `authorized=true` with no signature is a
    ///    forgery attempt, not a missing-auth case.)
    /// 2. **credential_id match** — `auth.credential_id` must equal the stored one. Otherwise →
    ///    [`PasskeyError::CredentialMismatch`].
    /// 3. **Challenge presence** — `auth.challenge` must be in `pending_challenges`. Otherwise →
    ///    [`PasskeyError::Replay`].
    /// 4. **Signature verification** — signature over `challenge || credential_id` must verify
    ///    against the stored pubkey. Otherwise → [`PasskeyError::Forged`].
    /// 5. **Consume the challenge** — on success, the challenge is removed from
    ///    `pending_challenges` (single-use, replay protection).
    pub fn verify(&mut self, auth: &PasskeyAuthorization) -> Result<(), PasskeyError> {
        // 1. Structural completeness. R31: any boolean "authorized=true" in the IPC envelope is
        //    irrelevant — we never look at boolean fields.
        if auth.challenge.len() != 32 || auth.credential_id.is_empty() {
            return Err(PasskeyError::Missing);
        }

        // 2. credential_id match.
        if auth.credential_id.as_bytes() != self.stored_credential_id.as_slice() {
            return Err(PasskeyError::CredentialMismatch);
        }

        // 3. Challenge presence (single-use, replay protection).
        let mut challenge = [0u8; 32];
        challenge.copy_from_slice(&auth.challenge);
        if !self.pending_challenges.contains(&challenge) {
            return Err(PasskeyError::Replay);
        }

        // 4. Signature verification over (challenge || credential_id). OneCipher simplified
        //    protocol — NOT full WebAuthn authenticator data.
        let mut message = Vec::with_capacity(auth.challenge.len() + auth.credential_id.len());
        message.extend_from_slice(&auth.challenge);
        message.extend_from_slice(auth.credential_id.as_bytes());

        let sig_ok = match &self.stored_pubkey {
            PasskeyPubkey::P256(vk) => {
                let sig = match p256::ecdsa::Signature::from_slice(&auth.signature) {
                    Ok(s) => s,
                    // Malformed or empty signature bytes — forgery attempt.
                    Err(_) => return Err(PasskeyError::Forged),
                };
                // UFCS to avoid importing the `signature::Verifier` trait at
                // crate root (keeps `passkey.rs` import surface minimal).
                p256::ecdsa::signature::Verifier::verify(vk, &message, &sig).is_ok()
            }
            PasskeyPubkey::Ed25519(vk) => {
                let sig = match ed25519_dalek::Signature::from_slice(&auth.signature) {
                    Ok(s) => s,
                    Err(_) => return Err(PasskeyError::Forged),
                };
                ed25519_dalek::Verifier::verify(vk, &message, &sig).is_ok()
            }
        };

        if !sig_ok {
            return Err(PasskeyError::Forged);
        }

        // 5. Consume the challenge (single-use).
        self.pending_challenges.remove(&challenge);
        Ok(())
    }

    /// Number of pending (unconsumed) challenges. Useful for tests / diagnostics.
    pub fn pending_count(&self) -> usize {
        self.pending_challenges.len()
    }
}

// ===========================================================================
// PasskeyPubkeyStore — persistent store for registered Passkey public keys.
// ===========================================================================

/// Errors that can arise when operating the [`PasskeyPubkeyStore`].
#[derive(Debug, thiserror::Error)]
pub enum PasskeyStoreError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("HOME not set")]
    HomeNotSet,
    #[error("unsupported algorithm: {0} (expected \"p256\" or \"ed25519\")")]
    UnsupportedAlgorithm(String),
    #[error("invalid public key: {0}")]
    InvalidPublicKey(String),
}

/// A registered Passkey public key persisted by the Key-Agent.
///
/// Per R30/R44: the Key-Agent stores the Passkey public key locally at
/// wallet-creation time and verifies `PasskeyAuthorization.signature` itself.
/// The `algorithm` field determines which variant of [`PasskeyPubkey`] the
/// raw `public_key` bytes decode into.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredPasskeyPubkey {
    /// Algorithm identifier: `"p256"` or `"ed25519"`.
    pub algorithm: String,
    /// Raw public key bytes (SEC1-encoded for P-256, 32 raw bytes for Ed25519).
    pub public_key: Vec<u8>,
    /// Wallet ID this passkey is bound to.
    pub wallet_id: String,
    /// Unix timestamp (seconds) when the passkey was registered.
    pub registered_at: u64,
}

/// Persistent, file-backed store for registered Passkey public keys.
///
/// Stored as a JSON map at `~/.onecipher/passkeys.json` (mode 0600, parent
/// dir mode 0700). The map keys are credential IDs (strings), and the values
/// are [`StoredPasskeyPubkey`] structs.
///
/// Per R56: synchronous std only, NO tokio / async.
pub struct PasskeyPubkeyStore {
    path: PathBuf,
}

impl PasskeyPubkeyStore {
    /// Open the default store at `~/.onecipher/passkeys.json`.
    pub fn open_default() -> Result<Self, PasskeyStoreError> {
        let home = std::env::var("HOME").map_err(|_| PasskeyStoreError::HomeNotSet)?;
        Ok(Self { path: PathBuf::from(home).join(".onecipher").join("passkeys.json") })
    }

    /// Open a store at a specific path.
    pub fn open(path: &Path) -> Self {
        Self { path: path.to_path_buf() }
    }

    /// Load the full credential map from disk. Returns an empty map if the
    /// file does not exist or cannot be parsed (best-effort, matching the
    /// `Option` return type of [`Self::get`]).
    fn load(&self) -> HashMap<String, StoredPasskeyPubkey> {
        match fs::read_to_string(&self.path) {
            Ok(contents) if !contents.trim().is_empty() => {
                serde_json::from_str(&contents).unwrap_or_default()
            }
            _ => HashMap::new(),
        }
    }

    /// Persist the full credential map to disk with mode 0600.
    fn save(&self, map: &HashMap<String, StoredPasskeyPubkey>) -> Result<(), PasskeyStoreError> {
        if let Some(parent) = self.path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
                let _ = fs::set_permissions(parent, fs::Permissions::from_mode(0o700));
            }
        }
        let json = serde_json::to_string_pretty(map)?;
        fs::write(&self.path, json.as_bytes())?;
        let _ = fs::set_permissions(&self.path, fs::Permissions::from_mode(0o600));
        Ok(())
    }

    /// Look up a stored passkey by credential ID.
    ///
    /// Returns `None` if the credential ID is not registered or the store
    /// file cannot be read (best-effort — callers treat absence as rejection).
    pub fn get(&self, credential_id: &str) -> Option<StoredPasskeyPubkey> {
        self.load().get(credential_id).cloned()
    }

    /// Register (or replace) a passkey public key for the given credential ID.
    pub fn register(
        &mut self,
        credential_id: &str,
        stored: StoredPasskeyPubkey,
    ) -> Result<(), PasskeyStoreError> {
        let mut map = self.load();
        map.insert(credential_id.to_string(), stored);
        self.save(&map)
    }

    /// Convert a [`StoredPasskeyPubkey`] into a [`PasskeyPubkey`] suitable for
    /// use with [`PasskeyVerifier`].
    ///
    /// The `algorithm` field determines the decoding:
    /// - `"p256"` — decoded as a SEC1-encoded P-256 verifying key.
    /// - `"ed25519"` — decoded as 32 raw Ed25519 verifying key bytes.
    pub fn to_passkey_pubkey(
        stored: &StoredPasskeyPubkey,
    ) -> Result<PasskeyPubkey, PasskeyStoreError> {
        match stored.algorithm.as_str() {
            "p256" => {
                let vk = p256::ecdsa::VerifyingKey::from_sec1_bytes(&stored.public_key)
                    .map_err(|e| PasskeyStoreError::InvalidPublicKey(e.to_string()))?;
                Ok(PasskeyPubkey::P256(vk))
            }
            "ed25519" => {
                if stored.public_key.len() != 32 {
                    return Err(PasskeyStoreError::InvalidPublicKey(format!(
                        "ed25519 public key must be 32 bytes, got {}",
                        stored.public_key.len()
                    )));
                }
                let mut arr = [0u8; 32];
                arr.copy_from_slice(&stored.public_key);
                let vk = ed25519_dalek::VerifyingKey::from_bytes(&arr)
                    .map_err(|e| PasskeyStoreError::InvalidPublicKey(e.to_string()))?;
                Ok(PasskeyPubkey::Ed25519(vk))
            }
            other => Err(PasskeyStoreError::UnsupportedAlgorithm(other.to_string())),
        }
    }
}
